# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:211276575937:android:20dca73222b852e6ac5040",
       firebase_cli_token: "1//03A74ywbGrh6MCgYIARAAGAMSNwF-L9IrqrKrRgo4kT2TeZE-iry9r6RFCU8mwTQVKez2ZjzSyEAUtBlQWyRl82leE2X4tdPyBFg",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "marwanalibb@gmail.com",
       release_notes: "first fastlane firebase distribution release"
     )
  end
end
